@token = {{$dotenv %JWT_TOKEN}}
@baseurl =  {{$dotenv %BACKEND_URL}}

### LIST

GET {{baseurl}}/v1/clientes
Accept: application/json
Authorization: Bearer {{token}}

### SHOW

GET {{baseurl}}/v1/clientes/21
Accept: application/json
Authorization: Bearer {{token}}

### CREATE

POST {{baseurl}}/v1/clientes
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parametros" : {
        "nome" : "Cliente 1",
        "cnpj" : "55555555.20/1554"
    }
}

### UPDATE

PUT {{baseurl}}/v1/clientes/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parametros" : {
        "nome" : "Cliente updated",
        "cpnj" : "44444444.20/1554"
    }
}

### DELETE

DELETE {{baseurl}}/v1/clientes/1
Accept: application/json
Authorization: Bearer {{token}}
