@token = {{$dotenv %JWT_TOKEN}}
@baseurl =  {{$dotenv %BACKEND_URL}}

### LIST

GET {{baseurl}}/v1/produtos ###?page=2&parametros[filter_nome]=ad&parametros[filter_categoria]=quos&parametros[filter_stock]=350&parametros[filter_valor]=855
Accept: application/json
Authorization: Bearer {{token}}

### SHOW

GET {{baseurl}}/v1/produtos/21
Accept: application/json
Authorization: Bearer {{token}}

### CREATE

POST {{baseurl}}/v1/produtos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parametros" : {
        "nome" : "Produto 3",
        "valor" : "644.00",
        "stock" : 10,
        "categoria" : "construction"
    }
}

### UPDATE

PUT {{baseurl}}/v1/produtos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parametros" : {
        "nome" : "Produto updated",
        "valor" : "110.00",
        "stock" : 12,
        "categoria" : "beach"
    }
}

### DELETE

DELETE {{baseurl}}/v1/produtos/1
Accept: application/json
Authorization: Bearer {{token}}
